default:
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/ocamlrun:latest"

build_image:
  stage: build
  script:
    - docker build -t $IMAGE_NAME ./programme
    - docker push "$IMAGE_NAME"

test-ocamlrun:
  stage: test
  script:
    - cd programme
    - cp test.ml main.ml
    - docker run --rm -v ".:/app" $IMAGE_NAME
  artifacts:
    paths:
      - programme/output.txt

pages:
  stage: deploy 
  script:
    - mkdir -p public
    - cp programme/output.txt public/index.html
  artifacts:
    paths:
      - public

