SHELL := /bin/bash
execute:
	uldr_compil uldr_tikztree figures/tree1.utree -o figures/tree1.tikz
	uldr_compil uldr_tikztree figures/tree2.utree -o figures/tree2.tikz
	uldr_compil uldr_tikztree figures/tree3.utree -o figures/tree3.tikz
	uldr_compil uldr_tikztree figures/tree4.utree -o figures/tree4.tikz
	uldr_compil uldr_maths doc.mdx latex -o TIPE_Ulysse_DURAND.tex tikz -pdf